## Install flex-table-card from here https://github.com/custom-cards/flex-table-card
resources:
  - url: /local/flex-table-card/flex-table-card.js
    type: js

views:
  - title: ESXi Stats Example
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: custom:flex-table-card
            title: ESXi Hosts
            clickable: true
            entities:
              include: sensor.esxi_vmhost*
            columns:
              - name: Name
                attr: name
              - name: Version
                attr: version
              - name: Uptime (H)
                attr: uptime_hours
              - name: CPU Use (GHz)
                attr: cpuusage_ghz
              - name: Mem Use (GB)
                attr: memusage_gb
              - name: VMs
                attr: vms
          - type: custom:flex-table-card
            title: ESXi Virtual Machines
            clickable: true
            entities:
              include: sensor.esxi_vm_*
            columns:
              - name: Name
                attr: name
              - name: Status
                attr: status
              - name: State
                attr: state
              - name: Uptime (H)
                attr: uptime_hours
              - name: CPU Usage (%)
                attr: cpu_use_pct
              - name: CPUs
                attr: cpu_count
              - name: Mem Use (MB)
                attr: memory_used_mb
              - name: Mem Total (MB)
                attr: memory_allocated_mb
              - name: Storage Used (GB)
                attr: used_space_gb
              - name: VM Tools
                attr: tools_status
              - name: Snapshots
                attr: snapshots
          - type: custom:flex-table-card
            title: ESXi Datastores
            clickable: true
            entities:
              include: sensor.esxi_datastore*
            columns:
              - name: Name
                attr: name
              - name: Free Space (GB)
                attr: free_space_gb
              - name: Capacity (GB)
                attr: total_space_gb
              - name: Hosts
                attr: connected_hosts
              - name: VMs
                attr: virtual_machines
              - name: Type
                attr: type